apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: integration-run
spec:
  parallelism: 4
  script:
    configMap:
      name: "scenarios-test"
      file: "archive.tar" # <-- change here
  arguments: -o experimental-prometheus-rw
  runner:
    metadata:
      labels:
        test-name: integration-test
    serviceAccountName: k6-runner
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
  starter:
    metadata:
      labels:
        test-name: integration-test
    serviceAccountName: k6-runner
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
