apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: integration-run
spec:
  parallelism: 4
  script:
    configMap:
      name: "social-test"
      file: "integration-run.js" # <-- change here
  arguments: -o experimental-prometheus-rw --tag testid=integration-test
  runner:
    metadata:
      labels:
        test-name: integration-test
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write
    serviceAccountName: k6-runner
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
  starter:
    metadata:
      labels:
        test-name: integration-test
    serviceAccountName: k6-runner
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
      runAsNonRoot: true
