apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
  namespace: monitoring
spec:
  datasources:
    - isDefault: true
      name: Prometheus
      uid: prometheus-monitoring
      type: prometheus
      url: 'http://prometheus-operated.monitoring.svc.cluster.local:9090'
  name: prometheus-datasource
