apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: social-database-postgres
  namespace: social-database
spec:
  port: 5432
  standby:
    enabled: false
  proxy:
    pgBouncer:
      port: 5432
      service:
        type: ClusterIP
      replicas: 1
  service:
    type: ClusterIP
  userInterface:
    pgAdmin:
      service:
        type: ClusterIP
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    switchover:
      type: Switchover
      enabled: true
    syncPeriodSeconds: 10
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      replicas: 3
  postgresVersion: 13
